import os
import json

# Ensure directories exist
os.makedirs("lib/engines", exist_ok=True)
os.makedirs("app/api/health", exist_ok=True)
os.makedirs("app/api/sectors", exist_ok=True)
os.makedirs("app/api/sectors/[id]", exist_ok=True)
os.makedirs("app/api/entities", exist_ok=True)
os.makedirs("app/api/entities/[id]", exist_ok=True)
os.makedirs("app/api/calculate/carbon-position", exist_ok=True)
os.makedirs("app/api/strategies/compare", exist_ok=True)
os.makedirs("app/api/scenarios/run", exist_ok=True)
os.makedirs("app/api/sources", exist_ok=True)
os.makedirs("app/api/methodologies", exist_ok=True)
os.makedirs("app/api/intelligence/analyze", exist_ok=True)
os.makedirs("app/api/intelligence/defaults/[sector]", exist_ok=True)
os.makedirs("app/api/intelligence/data-quality", exist_ok=True)
os.makedirs("app/api/intelligence/models", exist_ok=True)
os.makedirs("app/api/ai/explain", exist_ok=True)

# 1. Read JSON data files to embed them safely into TypeScript data modules
with open("backend/data/regulatory_truth/regulatory_status.json", "r", encoding="utf-8") as f:
    reg_status = json.load(f)
with open("backend/data/regulatory_truth/regulatory_targets.json", "r", encoding="utf-8") as f:
    reg_targets = json.load(f)
with open("backend/data/regulatory_truth/source_register.json", "r", encoding="utf-8") as f:
    sources = json.load(f)
with open("backend/data/regulatory_truth/methodologies.json", "r", encoding="utf-8") as f:
    methods = json.load(f)
with open("backend/data/synthetic/master_entities.json", "r", encoding="utf-8") as f:
    entities = json.load(f)

# Write lib/engines/data.ts
with open("lib/engines/data.ts", "w", encoding="utf-8") as f:
    f.write(f"""// Autogenerated from regulatory_truth and synthetic datasets
export const REGULATORY_STATUS_DATA = {json.dumps(reg_status, indent=2)};
export const REGULATORY_TARGETS_DATA = {json.dumps(reg_targets, indent=2)};
export const SOURCE_REGISTER_DATA = {json.dumps(sources, indent=2)};
export const METHODOLOGIES_DATA = {json.dumps(methods, indent=2)};
export const MASTER_ENTITIES_DATA = {json.dumps(entities, indent=2)};
""")

print("lib/engines/data.ts written successfully!")