// AANGARA — Shared Static Synthetic Data
// All data is SYNTHETIC / MODEL_ESTIMATE / ILLUSTRATIVE_VALUE as individually tagged.

export const MARKETPLACE_DATA = [
  {
    item_id: "MKT-PRJ-001", item_type: "DECARBONISATION_PROJECT",
    title: "Waste Heat Recovery — Cement Kiln Line 3 (9 MWe ORC)",
    sector: "cement", sub_sector: "Integrated OPC/PPC Plant",
    action_type: "Waste Heat Recovery (WHRS)",
    expected_reduction_tco2e_yr: 28000,
    capex_band_low_cr: 55, capex_band_high_cr: 75,
    mrv_readiness_score: 88,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 74,
    state: "Rajasthan", developer: "BEE-Registered EPC Vendor (Illustrative)",
    status: "AVAILABLE", data_status: "ILLUSTRATIVE_VALUE",
    illustrative_price_inr: 1800, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-001", technology_trl: 9,
    description: "Pre-FEED completed WHRS on a 1.2 Mtpa integrated cement plant. Technology: Turboden ORC (9 MWe). Captures kiln exhaust heat, reducing grid electricity purchase and cutting Scope 2 GEI. Methodology: BEE-CEM-WHRS-V3. MRV annual cost Rs 1.2 Cr. Verification by BEE-accredited agency.",
  },
  {
    item_id: "MKT-PRJ-002", item_type: "DECARBONISATION_PROJECT",
    title: "AFR Co-Processing — RDF/SRF Thermal Substitution (TSR 15%)",
    sector: "cement", sub_sector: "Integrated OPC/PPC Plant",
    action_type: "Alternative Fuel & Raw Material (AFR)",
    expected_reduction_tco2e_yr: 18500,
    capex_band_low_cr: 20, capex_band_high_cr: 35,
    mrv_readiness_score: 82,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 68,
    state: "Maharashtra", developer: "CPCB-Approved Co-Processing Facility (Illustrative)",
    status: "AVAILABLE", data_status: "ILLUSTRATIVE_VALUE",
    illustrative_price_inr: 1200, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-002", technology_trl: 8,
    description: "Thermal Substitution Rate increase from 4% to 15% using industrial waste (RDF, SRF, plastic reject). CPCB-approved co-processing. Emission factor credit via BEE TSR methodology. Reduces petcoke consumption by ~42,000 t/yr. Immediate GEI reduction with 18-month implementation.",
  },
  {
    item_id: "MKT-PRJ-003", item_type: "DECARBONISATION_PROJECT",
    title: "RFCC Waste Heat Recovery — Petroleum Refinery (HP Steam + Power)",
    sector: "petroleum_refinery", sub_sector: "Complex Refinery (FCC Configuration)",
    action_type: "Process Integration / WHR",
    expected_reduction_tco2e_yr: 45000,
    capex_band_low_cr: 140, capex_band_high_cr: 200,
    mrv_readiness_score: 86,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 78,
    state: "Gujarat", developer: "Licensed Refinery EPC Contractor (Illustrative)",
    status: "INDICATIVE", data_status: "MODEL_ESTIMATE",
    illustrative_price_inr: 2100, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-003", technology_trl: 8,
    description: "Capturing flue gas heat from RFCC catalyst regenerator for HP steam (45 bar, 400C). Reduces fired heater duty across CDU/VDU trains by 18%. Annual energy savings: ~Rs 38 Cr. Methodology: BEE-REF-WHR-V2. 22-month implementation; NABL-accredited metering pre-installed.",
  },
  {
    item_id: "MKT-PRJ-004", item_type: "DECARBONISATION_PROJECT",
    title: "Green Hydrogen Pilot — Alkaline Electrolyser (SMR Feedstock Switch)",
    sector: "petrochemicals", sub_sector: "Ammonia / Fertiliser Complex",
    action_type: "Green Hydrogen (Alkaline Electrolysis)",
    expected_reduction_tco2e_yr: 12000,
    capex_band_low_cr: 180, capex_band_high_cr: 260,
    mrv_readiness_score: 65,
    mechanism_tags: { ccts: true, rco: true, offset: false },
    compliance_value_score: 61,
    state: "Gujarat", developer: "MNRE-Registered RE Developer (Illustrative)",
    status: "INDICATIVE", data_status: "ILLUSTRATIVE_VALUE",
    illustrative_price_inr: 5800, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-004", technology_trl: 7,
    description: "Alkaline electrolyser (5 MW) fed by dedicated 15 MW solar PPA. Partial replacement of grey hydrogen from SMR. Dual-mechanism: reduces CCTS process GEI and adds 26,000 MWh/yr renewable consumption toward RCO obligation. TRL 7 at India commercial scale — elevated execution risk.",
  },
  {
    item_id: "MKT-PRJ-005", item_type: "DECARBONISATION_PROJECT",
    title: "Variable Frequency Drive Retrofit — Textile Mill Motors >7.5 kW",
    sector: "textile", sub_sector: "Composite Textile Mill",
    action_type: "Motor Efficiency / VFD",
    expected_reduction_tco2e_yr: 3800,
    capex_band_low_cr: 8, capex_band_high_cr: 15,
    mrv_readiness_score: 91,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 82,
    state: "Tamil Nadu", developer: "BEE-Empanelled Energy Auditor (Illustrative)",
    status: "AVAILABLE", data_status: "ILLUSTRATIVE_VALUE",
    illustrative_price_inr: 950, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-005", technology_trl: 9,
    description: "VFD on 380 motors >7.5 kW across spinning, weaving, and utility sections. Average energy saving 22%. Simple payback 2.8 years. Highest CVS in textile sector basket. MRV: sub-metering + BEE motor efficiency protocol. Zero technology risk.",
  },
  {
    item_id: "MKT-PRJ-006", item_type: "DECARBONISATION_PROJECT",
    title: "Aluminium Smelter Anode Effect Reduction — PFC Abatement Programme",
    sector: "aluminium", sub_sector: "Primary Aluminium Smelter (Prebake)",
    action_type: "Process Optimisation (PFC Reduction)",
    expected_reduction_tco2e_yr: 62000,
    capex_band_low_cr: 45, capex_band_high_cr: 70,
    mrv_readiness_score: 90,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 85,
    state: "Odisha", developer: "OEM-Certified Process Automation Vendor (Illustrative)",
    status: "AVAILABLE", data_status: "ILLUSTRATIVE_VALUE",
    illustrative_price_inr: 780, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-006", technology_trl: 9,
    description: "Upgrade smelter pot control to reduce anode effect frequency from 0.22 to 0.05 AE/pot-day. PFC (CF4 + C2F6) abatement: ~62,000 tCO2e/yr at 25-yr GWP. IPCC Tier 2B methodology. Extremely high CVS: low capex, high abatement, mature technology. Payback under 3 years.",
  },
  {
    item_id: "MKT-PRJ-007", item_type: "DECARBONISATION_PROJECT",
    title: "Pulp Mill Black Liquor Recovery Boiler Efficiency Upgrade",
    sector: "pulp_paper", sub_sector: "Integrated Chemical Pulp Mill (Kraft)",
    action_type: "Biomass / Black Liquor Recovery",
    expected_reduction_tco2e_yr: 22000,
    capex_band_low_cr: 95, capex_band_high_cr: 140,
    mrv_readiness_score: 79,
    mechanism_tags: { ccts: true, rco: true, offset: false },
    compliance_value_score: 70,
    state: "Odisha", developer: "Boiler OEM (European Kraft Recovery Technology)",
    status: "INDICATIVE", data_status: "MODEL_ESTIMATE",
    illustrative_price_inr: 2400, price_unit: "per tCO2e abated (lifecycle)",
    trust_pack_ref: "TRUST-MKT-PRJ-007", technology_trl: 8,
    description: "Recovery boiler efficiency upgrade from 65% to 82%. Increases steam from black liquor combustion, displacing coal-fired auxiliary boilers. Dual-mechanism: reduces CCTS GEI and adds ~35,000 MWh/yr biomass electricity (RCO eligible per MNRE biomass classification).",
  },
  {
    item_id: "MKT-PPA-001", item_type: "RENEWABLE_PPA",
    title: "50 MW Open Access Solar PPA — Rajasthan Utility Scale (25-yr)",
    sector: "cement", sub_sector: "Any large industrial (Rajasthan grid)",
    action_type: "OPEN_ACCESS_SOLAR",
    renewable_capacity_mw: 50, ppa_term_years: 25,
    tariff_inr_per_mwh: 2750,
    mechanism_tags: { ccts: true, rco: true, offset: false },
    compliance_value_score: 79,
    state: "Rajasthan", developer: "MNRE-Listed RE Developer (Indicative Only)",
    status: "INDICATIVE", data_status: "MODEL_ESTIMATE",
    price_unit: "per MWh (indicative PPA tariff)",
    trust_pack_ref: "TRUST-MKT-PPA-001", technology_trl: 9,
    description: "Open-access solar PPA from Rajasthan utility-scale park (CUF ~26%). Annual generation: ~113,880 MWh. Dual-mechanism: reduces Scope 2 GEI via CEA grid factor (0.716 tCO2e/MWh) and contributes to RPO/RCO solar sub-target. Wheeling ~Rs 0.45/kWh, banking per RERC tariff order.",
  },
  {
    item_id: "MKT-PPA-002", item_type: "RENEWABLE_PPA",
    title: "80 MW Hybrid RE PPA — Solar + Wind, Gujarat Coast (20-yr)",
    sector: "petroleum_refinery", sub_sector: "Any high-load industrial (Gujarat grid)",
    action_type: "HYBRID_RE",
    renewable_capacity_mw: 80, ppa_term_years: 20,
    tariff_inr_per_mwh: 3200,
    mechanism_tags: { ccts: true, rco: true, offset: false },
    compliance_value_score: 77,
    state: "Gujarat", developer: "MNRE-Registered Hybrid RE Developer (Illustrative)",
    status: "INDICATIVE", data_status: "ILLUSTRATIVE_VALUE",
    price_unit: "per MWh (blended hybrid tariff)",
    trust_pack_ref: "TRUST-MKT-PPA-002", technology_trl: 9,
    description: "Hybrid RE PPA: 50 MW coastal wind (CUF 38%) + 30 MW co-located solar (CUF 25%). Blended PLF 33%. Annual generation ~231,000 MWh. Near-continuous RE supply. Gujarat Open Access. RCO solar + wind + non-solar sub-targets all addressed in one agreement.",
  },
  {
    item_id: "MKT-PPA-003", item_type: "RENEWABLE_PPA",
    title: "MSEDCL Green Tariff — Maharashtra State FY2025-26 (Regulated)",
    sector: "textile", sub_sector: "Any MSEDCL-connected industrial",
    action_type: "GREEN_TARIFF",
    renewable_capacity_mw: 10, ppa_term_years: 5,
    tariff_inr_per_mwh: 4100,
    mechanism_tags: { ccts: true, rco: true, offset: false },
    compliance_value_score: 58,
    state: "Maharashtra", developer: "MSEDCL Green Tariff Scheme (Regulated Utility)",
    status: "AVAILABLE", data_status: "OBSERVED_MARKET_DATA",
    price_unit: "per MWh (MSEDCL approved rate FY2025-26)",
    trust_pack_ref: "TRUST-MKT-PPA-003", technology_trl: 9,
    description: "MSEDCL-regulated green tariff (MERC approved). Consumer pays premium above HT industrial tariff; MSEDCL procures equivalent RE from its RPO basket. No wheeling or banking complexity — fastest path to RCO compliance for Maharashtra consumers. Suitable for captive consumers <25 MW.",
  },
  {
    item_id: "MKT-PPA-004", item_type: "RENEWABLE_PPA",
    title: "25 MW Rooftop + Floating Solar — Captive Industrial (Tamil Nadu)",
    sector: "aluminium", sub_sector: "Any captive consumer (TANGEDCO grid)",
    action_type: "CAPTIVE_SOLAR",
    renewable_capacity_mw: 25, ppa_term_years: 15,
    tariff_inr_per_mwh: 2550,
    mechanism_tags: { ccts: true, rco: true, offset: false },
    compliance_value_score: 81,
    state: "Tamil Nadu", developer: "TANGEDCO-Empanelled Solar Developer (Illustrative)",
    status: "AVAILABLE", data_status: "MODEL_ESTIMATE",
    price_unit: "per MWh (captive LCOE estimate)",
    trust_pack_ref: "TRUST-MKT-PPA-004", technology_trl: 9,
    description: "Captive rooftop + floating solar on factory roofs and effluent ponds. No open-access wheeling — direct captive consumption. Annual generation ~50,000 MWh. Fully owned after 15 years. Strong NPV (Rs 22 Cr at 9.5% WACC). Tamil Nadu SERC captive regulations apply.",
  },
  {
    item_id: "MKT-CCC-001", item_type: "CCC_LISTING",
    title: "Modelled CCC Supply — Aluminium Sector Surplus (FY2025-26)",
    sector: "aluminium", action_type: "CCC_SUPPLY",
    expected_reduction_tco2e_yr: 45000,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 72,
    state: "Odisha / Jharkhand",
    status: "INDICATIVE", data_status: "MODEL_ESTIMATE",
    illustrative_price_inr: 920, price_unit: "per CCC (scenario model estimate)",
    trust_pack_ref: "TRUST-MKT-CCC-001", technology_trl: 9,
    description: "Aggregated modelled surplus from 4 synthetic aluminium smelters. Aluminium historically shows CCTS surplus from pre-bake pot modernisation. CCCs are MODELLED — not issued, not verified, not listed on IEXGREEN/PXIL. For analytical exploration only.",
  },
  {
    item_id: "MKT-CCC-002", item_type: "CCC_LISTING",
    title: "Modelled CCC Demand — Cement Sector Shortfall (FY2025-26)",
    sector: "cement", action_type: "CCC_DEMAND",
    expected_reduction_tco2e_yr: 85000,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 65,
    state: "National (Multiple States)",
    status: "INDICATIVE", data_status: "MODEL_ESTIMATE",
    illustrative_price_inr: 1050, price_unit: "per CCC (scenario model estimate)",
    trust_pack_ref: "TRUST-MKT-CCC-002", technology_trl: 9,
    description: "Aggregated modelled compliance shortfall across 8 synthetic cement entities. Sector shortfall driven by rising clinker-to-cement ratio constraints. Prices benchmarked to PAT Credit historical range scaled to CCTS. NOT live market data.",
  },
  {
    item_id: "MKT-CCC-003", item_type: "CCC_LISTING",
    title: "Modelled CCC Supply — Textile Sector (Energy Efficiency Surplus)",
    sector: "textile", action_type: "CCC_SUPPLY",
    expected_reduction_tco2e_yr: 12500,
    mechanism_tags: { ccts: true, rco: false, offset: false },
    compliance_value_score: 68,
    state: "Tamil Nadu / Gujarat",
    status: "INDICATIVE", data_status: "MODEL_ESTIMATE",
    illustrative_price_inr: 780, price_unit: "per CCC (scenario model estimate)",
    trust_pack_ref: "TRUST-MKT-CCC-003", technology_trl: 9,
    description: "Modelled CCC supply from textile mills with VFD retrofits and condensate recovery in PAT Cycle 6-7. Surplus tCO2e projected under CCTS GEI baseline. Lower price due to smaller lot sizes and higher per-unit transaction costs.",
  },
];

export const TERMINAL_WATCHLIST = [
  { entity_id: "SYN-CEM-001", entity_name: "Synthetic Cement Unit 01", sector: "Cement", actual_gei: 0.745, target_gei: 0.720, gei_delta: 0.025, compliance_status: "SHORTFALL", rco_share_pct: 12.5, rco_target_pct: 25.0, compliance_value_score: 62, shortfall_tco2e: 25000, data_status: "SYNTHETIC" },
  { entity_id: "SYN-REF-001", entity_name: "Synthetic Refinery Unit 01", sector: "Petroleum Refinery", actual_gei: 0.580, target_gei: 0.565, gei_delta: 0.015, compliance_status: "SHORTFALL", rco_share_pct: 15.0, rco_target_pct: 20.0, compliance_value_score: 71, shortfall_tco2e: 123000, data_status: "SYNTHETIC" },
  { entity_id: "SYN-ALU-001", entity_name: "Synthetic Aluminium Smelter 01", sector: "Aluminium", actual_gei: 8.85, target_gei: 9.20, gei_delta: -0.35, compliance_status: "SURPLUS", rco_share_pct: 28.0, rco_target_pct: 30.0, compliance_value_score: 84, shortfall_tco2e: 0, data_status: "SYNTHETIC" },
  { entity_id: "SYN-STL-001", entity_name: "Synthetic Steel Plant 01", sector: "Steel", actual_gei: 2.12, target_gei: 2.08, gei_delta: 0.04, compliance_status: "SHORTFALL", rco_share_pct: 8.5, rco_target_pct: 22.0, compliance_value_score: 58, shortfall_tco2e: 18400, data_status: "SYNTHETIC" },
  { entity_id: "SYN-TXT-001", entity_name: "Synthetic Textile Mill 01", sector: "Textile", actual_gei: 0.185, target_gei: 0.192, gei_delta: -0.007, compliance_status: "SURPLUS", rco_share_pct: 16.0, rco_target_pct: 18.0, compliance_value_score: 79, shortfall_tco2e: 0, data_status: "SYNTHETIC" },
  { entity_id: "SYN-CHL-001", entity_name: "Synthetic Chlor-Alkali Plant 01", sector: "Chlor-Alkali", actual_gei: 2.65, target_gei: 2.60, gei_delta: 0.05, compliance_status: "SHORTFALL", rco_share_pct: 14.2, rco_target_pct: 20.0, compliance_value_score: 65, shortfall_tco2e: 8700, data_status: "SYNTHETIC" },
  { entity_id: "SYN-PET-001", entity_name: "Synthetic Petrochemical Complex 01", sector: "Petrochemicals", actual_gei: 0.92, target_gei: 0.95, gei_delta: -0.03, compliance_status: "SURPLUS", rco_share_pct: 12.0, rco_target_pct: 18.0, compliance_value_score: 73, shortfall_tco2e: 0, data_status: "SYNTHETIC" },
  { entity_id: "SYN-PPR-001", entity_name: "Synthetic Pulp Paper Mill 01", sector: "Pulp & Paper", actual_gei: 1.48, target_gei: 1.42, gei_delta: 0.06, compliance_status: "SHORTFALL", rco_share_pct: 10.5, rco_target_pct: 15.0, compliance_value_score: 55, shortfall_tco2e: 6200, data_status: "SYNTHETIC" },
];

export const TERMINAL_CCC_CURVE = [
  { year: "FY26", scenario_label: "PAT Season 7 Mid-Cycle", price_bear_inr: 400, price_base_inr: 800, price_bull_inr: 1400 },
  { year: "FY27", scenario_label: "CCTS Phase 1 Launch", price_bear_inr: 600, price_base_inr: 1050, price_bull_inr: 1800 },
  { year: "FY28", scenario_label: "CCTS Expansion + Cement Tightening", price_bear_inr: 750, price_base_inr: 1350, price_bull_inr: 2400 },
  { year: "FY29", scenario_label: "Steel & Refinery Join CCTS", price_bear_inr: 900, price_base_inr: 1700, price_bull_inr: 3000 },
  { year: "FY30", scenario_label: "India NDC Alignment", price_bear_inr: 1100, price_base_inr: 2100, price_bull_inr: 3800 },
];

export const TERMINAL_BLOTTER = [
  { entry_id: "ORD-001", entity_id: "SYN-CEM-001", entity_name: "Synthetic Cement Unit 01", direction: "BUY", quantity_tco2e: 25000, scenario_price_inr: 1000, scenario_value_cr: 2.50, strategy: "BUY" },
  { entry_id: "ORD-002", entity_id: "SYN-REF-001", entity_name: "Synthetic Refinery Unit 01", direction: "BUY", quantity_tco2e: 123000, scenario_price_inr: 1000, scenario_value_cr: 12.30, strategy: "HYBRID" },
  { entry_id: "ORD-003", entity_id: "SYN-ALU-001", entity_name: "Synthetic Aluminium Smelter 01", direction: "SELL", quantity_tco2e: 32000, scenario_price_inr: 920, scenario_value_cr: 2.94, strategy: "SURPLUS_MONETIZE" },
  { entry_id: "ORD-004", entity_id: "SYN-STL-001", entity_name: "Synthetic Steel Plant 01", direction: "BUY", quantity_tco2e: 18400, scenario_price_inr: 1000, scenario_value_cr: 1.84, strategy: "BUY" },
  { entry_id: "ORD-005", entity_id: "SYN-CHL-001", entity_name: "Synthetic Chlor-Alkali Plant 01", direction: "BUY", quantity_tco2e: 8700, scenario_price_inr: 1000, scenario_value_cr: 0.87, strategy: "BUY" },
  { entry_id: "ORD-006", entity_id: "SYN-PPR-001", entity_name: "Synthetic Pulp Paper Mill 01", direction: "BUY", quantity_tco2e: 6200, scenario_price_inr: 1000, scenario_value_cr: 0.62, strategy: "BUY" },
];

export const TERMINAL_REG_FEED = [
  { id: "REG-001", date: "2025-07-29", headline: "MNRE RPO Trajectory 2022-2030: Solar sub-target increased to 8% for petroleum refinery sector (FY2025-26)", source: "MNRE Gazette Notification", status: "FINAL", url: "https://mnre.gov.in/orders/rpo-order-2022/", sector: "Petroleum Refinery" },
  { id: "REG-002", date: "2025-06-15", headline: "MoEFCC CCTS Phase 1 GEI Targets confirmed for Cement: 0.720 tCO2e/t cement for FY2025-26 (G.S.R. 25(E))", source: "MoEFCC / BEE Gazette", status: "FINAL", url: "https://beeindia.gov.in/show_content.php?lang=1&level=1&lid=294&ls_id=116", sector: "Cement" },
  { id: "REG-003", date: "2025-05-20", headline: "BEE PAT Cycle 8 — New energy intensity targets for aluminium smelters (2025-2030 compliance period)", source: "BEE India", status: "DRAFT", url: "https://beeindia.gov.in", sector: "Aluminium" },
  { id: "REG-004", date: "2025-04-10", headline: "CERC REC Regulations 2022 Amendment: Floor price for solar RECs revised upward to Rs 900/MWh", source: "CERC Order (RP/10/2025)", status: "FINAL", url: "https://cercind.gov.in", sector: "All Sectors" },
  { id: "REG-005", date: "2025-03-01", headline: "Steel sector CCTS inclusion under review — MoEFCC technical committee formed; DRI and EAF routes under separate sub-target discussion", source: "MoEFCC", status: "WATCHLIST", url: "https://moef.gov.in", sector: "Steel" },
  { id: "REG-006", date: "2025-02-14", headline: "IEXGREEN CCC trading platform — Platform readiness report submitted to MoEFCC; settlement rules under consultation", source: "IEX Green Market Bulletin", status: "DRAFT", url: "https://iexgreen.com", sector: "All Sectors" },
  { id: "REG-007", date: "2025-01-20", headline: "Pulp & Paper GEI baseline notification: Chemical pulp (Kraft) target 1.42 tCO2e/tonne for FY2025-26", source: "BEE Gazette", status: "FINAL", url: "https://beeindia.gov.in", sector: "Pulp & Paper" },
];
